# Generated by Django 5.2.1 on 2025-06-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_alter_aiservicelog_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiservicelog',
            name='response_time',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
