# Generated by Django 5.2.1 on 2025-06-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0003_alter_aiservicelog_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiservicelog',
            name='error_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aiservicelog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
