# Generated by Django 5.2.1 on 2025-06-02 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, help_text='VAT ID, Tax ID, etc.', max_length=50)),
                ('billing_address_line1', models.CharField(max_length=200)),
                ('billing_address_line2', models.CharField(blank=True, max_length=200)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(blank=True, max_length=100)),
                ('billing_country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland'), ('CH', 'Switzerland'), ('AT', 'Austria'), ('BE', 'Belgium'), ('IE', 'Ireland'), ('PT', 'Portugal'), ('LU', 'Luxembourg'), ('IS', 'Iceland')], max_length=2)),
                ('billing_postal_code', models.CharField(max_length=20)),
                ('preferred_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Profile',
                'verbose_name_plural': 'Billing Profiles',
            },
        ),
    ]
