# Generated by Django 5.2.1 on 2025-07-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('demo', 'Demo'), ('api', 'API'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card')], max_length=50),
        ),
    ]
