# Generated by Django 5.2.1 on 2025-06-06 08:40

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosummary',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='audiosummary',
            name='audio_file',
            field=models.FileField(blank=True, upload_to=documents.models.audio_upload_path),
        ),
        migrations.AlterField(
            model_name='audiosummary',
            name='audio_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
    ]
